/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProprietarioRouteImport } from './routes/proprietario'
import { Route as PassageiroRouteImport } from './routes/passageiro'
import { Route as OficinaRouteImport } from './routes/oficina'
import { Route as MotoristaRouteImport } from './routes/motorista'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProprietarioIndexRouteImport } from './routes/proprietario.index'
import { Route as PassageiroIndexRouteImport } from './routes/passageiro.index'
import { Route as OficinaIndexRouteImport } from './routes/oficina.index'
import { Route as MotoristaIndexRouteImport } from './routes/motorista.index'
import { Route as LojaIndexRouteImport } from './routes/loja.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProprietarioPerfilRouteImport } from './routes/proprietario.perfil'
import { Route as ProprietarioNotificacoesRouteImport } from './routes/proprietario.notificacoes'
import { Route as ProprietarioMotoristasRouteImport } from './routes/proprietario.motoristas'
import { Route as ProprietarioMarketplaceRouteImport } from './routes/proprietario.marketplace'
import { Route as ProprietarioFinanceiroRouteImport } from './routes/proprietario.financeiro'
import { Route as ProprietarioAgendaRouteImport } from './routes/proprietario.agenda'
import { Route as PassageiroPerfilRouteImport } from './routes/passageiro.perfil'
import { Route as PassageiroParceirosRouteImport } from './routes/passageiro.parceiros'
import { Route as PassageiroCashbackRouteImport } from './routes/passageiro.cashback'
import { Route as OficinaPerfilRouteImport } from './routes/oficina.perfil'
import { Route as OficinaFinanceiroRouteImport } from './routes/oficina.financeiro'
import { Route as OficinaAgendaRouteImport } from './routes/oficina.agenda'
import { Route as MotoristaPerfilRouteImport } from './routes/motorista.perfil'
import { Route as MotoristaOrcamentosRouteImport } from './routes/motorista.orcamentos'
import { Route as MotoristaJornadaRouteImport } from './routes/motorista.jornada'
import { Route as MotoristaCorridasRouteImport } from './routes/motorista.corridas'
import { Route as MotoristaCheckinRouteImport } from './routes/motorista.checkin'
import { Route as MotoristaBeneficiosRouteImport } from './routes/motorista.beneficios'
import { Route as MotoristaAlugueisRouteImport } from './routes/motorista.alugueis'
import { Route as LojaPerfilRouteImport } from './routes/loja.perfil'
import { Route as LojaNegocioRouteImport } from './routes/loja.negocio'
import { Route as LojaEstoqueRouteImport } from './routes/loja.estoque'
import { Route as LojaCampanhasRouteImport } from './routes/loja.campanhas'
import { Route as AdminParceirosRouteImport } from './routes/admin.parceiros'
import { Route as AdminModeracaoRouteImport } from './routes/admin.moderacao'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as ProprietarioFrotaIndexRouteImport } from './routes/proprietario.frota.index'
import { Route as ProprietarioContratosIndexRouteImport } from './routes/proprietario.contratos.index'
import { Route as OficinaServicosIndexRouteImport } from './routes/oficina.servicos.index'
import { Route as LojaCatalogoIndexRouteImport } from './routes/loja.catalogo.index'
import { Route as ProprietarioSolicitacoesIdRouteImport } from './routes/proprietario.solicitacoes.$id'
import { Route as ProprietarioFrotaNovoRouteImport } from './routes/proprietario.frota.novo'
import { Route as ProprietarioFrotaCarroIdRouteImport } from './routes/proprietario.frota.$carroId'
import { Route as ProprietarioContratosNovoRouteImport } from './routes/proprietario.contratos.novo'
import { Route as ProprietarioContratosIdRouteImport } from './routes/proprietario.contratos.$id'
import { Route as OficinaServicosOsIdRouteImport } from './routes/oficina.servicos.$osId'
import { Route as MotoristaCorridasIdRouteImport } from './routes/motorista.corridas.$id'
import { Route as MotoristaBeneficiosParceiroIdRouteImport } from './routes/motorista.beneficios.$parceiroId'
import { Route as MotoristaAlugueisCarroIdRouteImport } from './routes/motorista.alugueis.$carroId'
import { Route as LojaCatalogoNovoRouteImport } from './routes/loja.catalogo.novo'
import { Route as LojaCatalogoItemIdRouteImport } from './routes/loja.catalogo.$itemId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioRoute = ProprietarioRouteImport.update({
  id: '/proprietario',
  path: '/proprietario',
  getParentRoute: () => rootRouteImport,
} as any)
const PassageiroRoute = PassageiroRouteImport.update({
  id: '/passageiro',
  path: '/passageiro',
  getParentRoute: () => rootRouteImport,
} as any)
const OficinaRoute = OficinaRouteImport.update({
  id: '/oficina',
  path: '/oficina',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaRoute = MotoristaRouteImport.update({
  id: '/motorista',
  path: '/motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietarioIndexRoute = ProprietarioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProprietarioRoute,
} as any)
const PassageiroIndexRoute = PassageiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PassageiroRoute,
} as any)
const OficinaIndexRoute = OficinaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OficinaRoute,
} as any)
const MotoristaIndexRoute = MotoristaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MotoristaRoute,
} as any)
const LojaIndexRoute = LojaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LojaRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProprietarioPerfilRoute = ProprietarioPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ProprietarioRoute,
} as any)
const ProprietarioNotificacoesRoute =
  ProprietarioNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => ProprietarioRoute,
  } as any)
const ProprietarioMotoristasRoute = ProprietarioMotoristasRouteImport.update({
  id: '/motoristas',
  path: '/motoristas',
  getParentRoute: () => ProprietarioRoute,
} as any)
const ProprietarioMarketplaceRoute = ProprietarioMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => ProprietarioRoute,
} as any)
const ProprietarioFinanceiroRoute = ProprietarioFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => ProprietarioRoute,
} as any)
const ProprietarioAgendaRoute = ProprietarioAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => ProprietarioRoute,
} as any)
const PassageiroPerfilRoute = PassageiroPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroParceirosRoute = PassageiroParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => PassageiroRoute,
} as any)
const PassageiroCashbackRoute = PassageiroCashbackRouteImport.update({
  id: '/cashback',
  path: '/cashback',
  getParentRoute: () => PassageiroRoute,
} as any)
const OficinaPerfilRoute = OficinaPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => OficinaRoute,
} as any)
const OficinaFinanceiroRoute = OficinaFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => OficinaRoute,
} as any)
const OficinaAgendaRoute = OficinaAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => OficinaRoute,
} as any)
const MotoristaPerfilRoute = MotoristaPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => MotoristaRoute,
} as any)
const MotoristaOrcamentosRoute = MotoristaOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => MotoristaRoute,
} as any)
const MotoristaJornadaRoute = MotoristaJornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => MotoristaRoute,
} as any)
const MotoristaCorridasRoute = MotoristaCorridasRouteImport.update({
  id: '/corridas',
  path: '/corridas',
  getParentRoute: () => MotoristaRoute,
} as any)
const MotoristaCheckinRoute = MotoristaCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => MotoristaRoute,
} as any)
const MotoristaBeneficiosRoute = MotoristaBeneficiosRouteImport.update({
  id: '/beneficios',
  path: '/beneficios',
  getParentRoute: () => MotoristaRoute,
} as any)
const MotoristaAlugueisRoute = MotoristaAlugueisRouteImport.update({
  id: '/alugueis',
  path: '/alugueis',
  getParentRoute: () => MotoristaRoute,
} as any)
const LojaPerfilRoute = LojaPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => LojaRoute,
} as any)
const LojaNegocioRoute = LojaNegocioRouteImport.update({
  id: '/negocio',
  path: '/negocio',
  getParentRoute: () => LojaRoute,
} as any)
const LojaEstoqueRoute = LojaEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => LojaRoute,
} as any)
const LojaCampanhasRoute = LojaCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => LojaRoute,
} as any)
const AdminParceirosRoute = AdminParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModeracaoRoute = AdminModeracaoRouteImport.update({
  id: '/moderacao',
  path: '/moderacao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const ProprietarioFrotaIndexRoute = ProprietarioFrotaIndexRouteImport.update({
  id: '/frota/',
  path: '/frota/',
  getParentRoute: () => ProprietarioRoute,
} as any)
const ProprietarioContratosIndexRoute =
  ProprietarioContratosIndexRouteImport.update({
    id: '/contratos/',
    path: '/contratos/',
    getParentRoute: () => ProprietarioRoute,
  } as any)
const OficinaServicosIndexRoute = OficinaServicosIndexRouteImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => OficinaRoute,
} as any)
const LojaCatalogoIndexRoute = LojaCatalogoIndexRouteImport.update({
  id: '/catalogo/',
  path: '/catalogo/',
  getParentRoute: () => LojaRoute,
} as any)
const ProprietarioSolicitacoesIdRoute =
  ProprietarioSolicitacoesIdRouteImport.update({
    id: '/solicitacoes/$id',
    path: '/solicitacoes/$id',
    getParentRoute: () => ProprietarioRoute,
  } as any)
const ProprietarioFrotaNovoRoute = ProprietarioFrotaNovoRouteImport.update({
  id: '/frota/novo',
  path: '/frota/novo',
  getParentRoute: () => ProprietarioRoute,
} as any)
const ProprietarioFrotaCarroIdRoute =
  ProprietarioFrotaCarroIdRouteImport.update({
    id: '/frota/$carroId',
    path: '/frota/$carroId',
    getParentRoute: () => ProprietarioRoute,
  } as any)
const ProprietarioContratosNovoRoute =
  ProprietarioContratosNovoRouteImport.update({
    id: '/contratos/novo',
    path: '/contratos/novo',
    getParentRoute: () => ProprietarioRoute,
  } as any)
const ProprietarioContratosIdRoute = ProprietarioContratosIdRouteImport.update({
  id: '/contratos/$id',
  path: '/contratos/$id',
  getParentRoute: () => ProprietarioRoute,
} as any)
const OficinaServicosOsIdRoute = OficinaServicosOsIdRouteImport.update({
  id: '/servicos/$osId',
  path: '/servicos/$osId',
  getParentRoute: () => OficinaRoute,
} as any)
const MotoristaCorridasIdRoute = MotoristaCorridasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MotoristaCorridasRoute,
} as any)
const MotoristaBeneficiosParceiroIdRoute =
  MotoristaBeneficiosParceiroIdRouteImport.update({
    id: '/$parceiroId',
    path: '/$parceiroId',
    getParentRoute: () => MotoristaBeneficiosRoute,
  } as any)
const MotoristaAlugueisCarroIdRoute =
  MotoristaAlugueisCarroIdRouteImport.update({
    id: '/$carroId',
    path: '/$carroId',
    getParentRoute: () => MotoristaAlugueisRoute,
  } as any)
const LojaCatalogoNovoRoute = LojaCatalogoNovoRouteImport.update({
  id: '/catalogo/novo',
  path: '/catalogo/novo',
  getParentRoute: () => LojaRoute,
} as any)
const LojaCatalogoItemIdRoute = LojaCatalogoItemIdRouteImport.update({
  id: '/catalogo/$itemId',
  path: '/catalogo/$itemId',
  getParentRoute: () => LojaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/loja': typeof LojaRouteWithChildren
  '/motorista': typeof MotoristaRouteWithChildren
  '/oficina': typeof OficinaRouteWithChildren
  '/passageiro': typeof PassageiroRouteWithChildren
  '/proprietario': typeof ProprietarioRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/moderacao': typeof AdminModeracaoRoute
  '/admin/parceiros': typeof AdminParceirosRoute
  '/loja/campanhas': typeof LojaCampanhasRoute
  '/loja/estoque': typeof LojaEstoqueRoute
  '/loja/negocio': typeof LojaNegocioRoute
  '/loja/perfil': typeof LojaPerfilRoute
  '/motorista/alugueis': typeof MotoristaAlugueisRouteWithChildren
  '/motorista/beneficios': typeof MotoristaBeneficiosRouteWithChildren
  '/motorista/checkin': typeof MotoristaCheckinRoute
  '/motorista/corridas': typeof MotoristaCorridasRouteWithChildren
  '/motorista/jornada': typeof MotoristaJornadaRoute
  '/motorista/orcamentos': typeof MotoristaOrcamentosRoute
  '/motorista/perfil': typeof MotoristaPerfilRoute
  '/oficina/agenda': typeof OficinaAgendaRoute
  '/oficina/financeiro': typeof OficinaFinanceiroRoute
  '/oficina/perfil': typeof OficinaPerfilRoute
  '/passageiro/cashback': typeof PassageiroCashbackRoute
  '/passageiro/parceiros': typeof PassageiroParceirosRoute
  '/passageiro/perfil': typeof PassageiroPerfilRoute
  '/proprietario/agenda': typeof ProprietarioAgendaRoute
  '/proprietario/financeiro': typeof ProprietarioFinanceiroRoute
  '/proprietario/marketplace': typeof ProprietarioMarketplaceRoute
  '/proprietario/motoristas': typeof ProprietarioMotoristasRoute
  '/proprietario/notificacoes': typeof ProprietarioNotificacoesRoute
  '/proprietario/perfil': typeof ProprietarioPerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/loja/': typeof LojaIndexRoute
  '/motorista/': typeof MotoristaIndexRoute
  '/oficina/': typeof OficinaIndexRoute
  '/passageiro/': typeof PassageiroIndexRoute
  '/proprietario/': typeof ProprietarioIndexRoute
  '/loja/catalogo/$itemId': typeof LojaCatalogoItemIdRoute
  '/loja/catalogo/novo': typeof LojaCatalogoNovoRoute
  '/motorista/alugueis/$carroId': typeof MotoristaAlugueisCarroIdRoute
  '/motorista/beneficios/$parceiroId': typeof MotoristaBeneficiosParceiroIdRoute
  '/motorista/corridas/$id': typeof MotoristaCorridasIdRoute
  '/oficina/servicos/$osId': typeof OficinaServicosOsIdRoute
  '/proprietario/contratos/$id': typeof ProprietarioContratosIdRoute
  '/proprietario/contratos/novo': typeof ProprietarioContratosNovoRoute
  '/proprietario/frota/$carroId': typeof ProprietarioFrotaCarroIdRoute
  '/proprietario/frota/novo': typeof ProprietarioFrotaNovoRoute
  '/proprietario/solicitacoes/$id': typeof ProprietarioSolicitacoesIdRoute
  '/loja/catalogo/': typeof LojaCatalogoIndexRoute
  '/oficina/servicos/': typeof OficinaServicosIndexRoute
  '/proprietario/contratos/': typeof ProprietarioContratosIndexRoute
  '/proprietario/frota/': typeof ProprietarioFrotaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/moderacao': typeof AdminModeracaoRoute
  '/admin/parceiros': typeof AdminParceirosRoute
  '/loja/campanhas': typeof LojaCampanhasRoute
  '/loja/estoque': typeof LojaEstoqueRoute
  '/loja/negocio': typeof LojaNegocioRoute
  '/loja/perfil': typeof LojaPerfilRoute
  '/motorista/alugueis': typeof MotoristaAlugueisRouteWithChildren
  '/motorista/beneficios': typeof MotoristaBeneficiosRouteWithChildren
  '/motorista/checkin': typeof MotoristaCheckinRoute
  '/motorista/corridas': typeof MotoristaCorridasRouteWithChildren
  '/motorista/jornada': typeof MotoristaJornadaRoute
  '/motorista/orcamentos': typeof MotoristaOrcamentosRoute
  '/motorista/perfil': typeof MotoristaPerfilRoute
  '/oficina/agenda': typeof OficinaAgendaRoute
  '/oficina/financeiro': typeof OficinaFinanceiroRoute
  '/oficina/perfil': typeof OficinaPerfilRoute
  '/passageiro/cashback': typeof PassageiroCashbackRoute
  '/passageiro/parceiros': typeof PassageiroParceirosRoute
  '/passageiro/perfil': typeof PassageiroPerfilRoute
  '/proprietario/agenda': typeof ProprietarioAgendaRoute
  '/proprietario/financeiro': typeof ProprietarioFinanceiroRoute
  '/proprietario/marketplace': typeof ProprietarioMarketplaceRoute
  '/proprietario/motoristas': typeof ProprietarioMotoristasRoute
  '/proprietario/notificacoes': typeof ProprietarioNotificacoesRoute
  '/proprietario/perfil': typeof ProprietarioPerfilRoute
  '/admin': typeof AdminIndexRoute
  '/loja': typeof LojaIndexRoute
  '/motorista': typeof MotoristaIndexRoute
  '/oficina': typeof OficinaIndexRoute
  '/passageiro': typeof PassageiroIndexRoute
  '/proprietario': typeof ProprietarioIndexRoute
  '/loja/catalogo/$itemId': typeof LojaCatalogoItemIdRoute
  '/loja/catalogo/novo': typeof LojaCatalogoNovoRoute
  '/motorista/alugueis/$carroId': typeof MotoristaAlugueisCarroIdRoute
  '/motorista/beneficios/$parceiroId': typeof MotoristaBeneficiosParceiroIdRoute
  '/motorista/corridas/$id': typeof MotoristaCorridasIdRoute
  '/oficina/servicos/$osId': typeof OficinaServicosOsIdRoute
  '/proprietario/contratos/$id': typeof ProprietarioContratosIdRoute
  '/proprietario/contratos/novo': typeof ProprietarioContratosNovoRoute
  '/proprietario/frota/$carroId': typeof ProprietarioFrotaCarroIdRoute
  '/proprietario/frota/novo': typeof ProprietarioFrotaNovoRoute
  '/proprietario/solicitacoes/$id': typeof ProprietarioSolicitacoesIdRoute
  '/loja/catalogo': typeof LojaCatalogoIndexRoute
  '/oficina/servicos': typeof OficinaServicosIndexRoute
  '/proprietario/contratos': typeof ProprietarioContratosIndexRoute
  '/proprietario/frota': typeof ProprietarioFrotaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/loja': typeof LojaRouteWithChildren
  '/motorista': typeof MotoristaRouteWithChildren
  '/oficina': typeof OficinaRouteWithChildren
  '/passageiro': typeof PassageiroRouteWithChildren
  '/proprietario': typeof ProprietarioRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/moderacao': typeof AdminModeracaoRoute
  '/admin/parceiros': typeof AdminParceirosRoute
  '/loja/campanhas': typeof LojaCampanhasRoute
  '/loja/estoque': typeof LojaEstoqueRoute
  '/loja/negocio': typeof LojaNegocioRoute
  '/loja/perfil': typeof LojaPerfilRoute
  '/motorista/alugueis': typeof MotoristaAlugueisRouteWithChildren
  '/motorista/beneficios': typeof MotoristaBeneficiosRouteWithChildren
  '/motorista/checkin': typeof MotoristaCheckinRoute
  '/motorista/corridas': typeof MotoristaCorridasRouteWithChildren
  '/motorista/jornada': typeof MotoristaJornadaRoute
  '/motorista/orcamentos': typeof MotoristaOrcamentosRoute
  '/motorista/perfil': typeof MotoristaPerfilRoute
  '/oficina/agenda': typeof OficinaAgendaRoute
  '/oficina/financeiro': typeof OficinaFinanceiroRoute
  '/oficina/perfil': typeof OficinaPerfilRoute
  '/passageiro/cashback': typeof PassageiroCashbackRoute
  '/passageiro/parceiros': typeof PassageiroParceirosRoute
  '/passageiro/perfil': typeof PassageiroPerfilRoute
  '/proprietario/agenda': typeof ProprietarioAgendaRoute
  '/proprietario/financeiro': typeof ProprietarioFinanceiroRoute
  '/proprietario/marketplace': typeof ProprietarioMarketplaceRoute
  '/proprietario/motoristas': typeof ProprietarioMotoristasRoute
  '/proprietario/notificacoes': typeof ProprietarioNotificacoesRoute
  '/proprietario/perfil': typeof ProprietarioPerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/loja/': typeof LojaIndexRoute
  '/motorista/': typeof MotoristaIndexRoute
  '/oficina/': typeof OficinaIndexRoute
  '/passageiro/': typeof PassageiroIndexRoute
  '/proprietario/': typeof ProprietarioIndexRoute
  '/loja/catalogo/$itemId': typeof LojaCatalogoItemIdRoute
  '/loja/catalogo/novo': typeof LojaCatalogoNovoRoute
  '/motorista/alugueis/$carroId': typeof MotoristaAlugueisCarroIdRoute
  '/motorista/beneficios/$parceiroId': typeof MotoristaBeneficiosParceiroIdRoute
  '/motorista/corridas/$id': typeof MotoristaCorridasIdRoute
  '/oficina/servicos/$osId': typeof OficinaServicosOsIdRoute
  '/proprietario/contratos/$id': typeof ProprietarioContratosIdRoute
  '/proprietario/contratos/novo': typeof ProprietarioContratosNovoRoute
  '/proprietario/frota/$carroId': typeof ProprietarioFrotaCarroIdRoute
  '/proprietario/frota/novo': typeof ProprietarioFrotaNovoRoute
  '/proprietario/solicitacoes/$id': typeof ProprietarioSolicitacoesIdRoute
  '/loja/catalogo/': typeof LojaCatalogoIndexRoute
  '/oficina/servicos/': typeof OficinaServicosIndexRoute
  '/proprietario/contratos/': typeof ProprietarioContratosIndexRoute
  '/proprietario/frota/': typeof ProprietarioFrotaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/loja'
    | '/motorista'
    | '/oficina'
    | '/passageiro'
    | '/proprietario'
    | '/sitemap.xml'
    | '/admin/financeiro'
    | '/admin/moderacao'
    | '/admin/parceiros'
    | '/loja/campanhas'
    | '/loja/estoque'
    | '/loja/negocio'
    | '/loja/perfil'
    | '/motorista/alugueis'
    | '/motorista/beneficios'
    | '/motorista/checkin'
    | '/motorista/corridas'
    | '/motorista/jornada'
    | '/motorista/orcamentos'
    | '/motorista/perfil'
    | '/oficina/agenda'
    | '/oficina/financeiro'
    | '/oficina/perfil'
    | '/passageiro/cashback'
    | '/passageiro/parceiros'
    | '/passageiro/perfil'
    | '/proprietario/agenda'
    | '/proprietario/financeiro'
    | '/proprietario/marketplace'
    | '/proprietario/motoristas'
    | '/proprietario/notificacoes'
    | '/proprietario/perfil'
    | '/admin/'
    | '/loja/'
    | '/motorista/'
    | '/oficina/'
    | '/passageiro/'
    | '/proprietario/'
    | '/loja/catalogo/$itemId'
    | '/loja/catalogo/novo'
    | '/motorista/alugueis/$carroId'
    | '/motorista/beneficios/$parceiroId'
    | '/motorista/corridas/$id'
    | '/oficina/servicos/$osId'
    | '/proprietario/contratos/$id'
    | '/proprietario/contratos/novo'
    | '/proprietario/frota/$carroId'
    | '/proprietario/frota/novo'
    | '/proprietario/solicitacoes/$id'
    | '/loja/catalogo/'
    | '/oficina/servicos/'
    | '/proprietario/contratos/'
    | '/proprietario/frota/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin/financeiro'
    | '/admin/moderacao'
    | '/admin/parceiros'
    | '/loja/campanhas'
    | '/loja/estoque'
    | '/loja/negocio'
    | '/loja/perfil'
    | '/motorista/alugueis'
    | '/motorista/beneficios'
    | '/motorista/checkin'
    | '/motorista/corridas'
    | '/motorista/jornada'
    | '/motorista/orcamentos'
    | '/motorista/perfil'
    | '/oficina/agenda'
    | '/oficina/financeiro'
    | '/oficina/perfil'
    | '/passageiro/cashback'
    | '/passageiro/parceiros'
    | '/passageiro/perfil'
    | '/proprietario/agenda'
    | '/proprietario/financeiro'
    | '/proprietario/marketplace'
    | '/proprietario/motoristas'
    | '/proprietario/notificacoes'
    | '/proprietario/perfil'
    | '/admin'
    | '/loja'
    | '/motorista'
    | '/oficina'
    | '/passageiro'
    | '/proprietario'
    | '/loja/catalogo/$itemId'
    | '/loja/catalogo/novo'
    | '/motorista/alugueis/$carroId'
    | '/motorista/beneficios/$parceiroId'
    | '/motorista/corridas/$id'
    | '/oficina/servicos/$osId'
    | '/proprietario/contratos/$id'
    | '/proprietario/contratos/novo'
    | '/proprietario/frota/$carroId'
    | '/proprietario/frota/novo'
    | '/proprietario/solicitacoes/$id'
    | '/loja/catalogo'
    | '/oficina/servicos'
    | '/proprietario/contratos'
    | '/proprietario/frota'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/loja'
    | '/motorista'
    | '/oficina'
    | '/passageiro'
    | '/proprietario'
    | '/sitemap.xml'
    | '/admin/financeiro'
    | '/admin/moderacao'
    | '/admin/parceiros'
    | '/loja/campanhas'
    | '/loja/estoque'
    | '/loja/negocio'
    | '/loja/perfil'
    | '/motorista/alugueis'
    | '/motorista/beneficios'
    | '/motorista/checkin'
    | '/motorista/corridas'
    | '/motorista/jornada'
    | '/motorista/orcamentos'
    | '/motorista/perfil'
    | '/oficina/agenda'
    | '/oficina/financeiro'
    | '/oficina/perfil'
    | '/passageiro/cashback'
    | '/passageiro/parceiros'
    | '/passageiro/perfil'
    | '/proprietario/agenda'
    | '/proprietario/financeiro'
    | '/proprietario/marketplace'
    | '/proprietario/motoristas'
    | '/proprietario/notificacoes'
    | '/proprietario/perfil'
    | '/admin/'
    | '/loja/'
    | '/motorista/'
    | '/oficina/'
    | '/passageiro/'
    | '/proprietario/'
    | '/loja/catalogo/$itemId'
    | '/loja/catalogo/novo'
    | '/motorista/alugueis/$carroId'
    | '/motorista/beneficios/$parceiroId'
    | '/motorista/corridas/$id'
    | '/oficina/servicos/$osId'
    | '/proprietario/contratos/$id'
    | '/proprietario/contratos/novo'
    | '/proprietario/frota/$carroId'
    | '/proprietario/frota/novo'
    | '/proprietario/solicitacoes/$id'
    | '/loja/catalogo/'
    | '/oficina/servicos/'
    | '/proprietario/contratos/'
    | '/proprietario/frota/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  LojaRoute: typeof LojaRouteWithChildren
  MotoristaRoute: typeof MotoristaRouteWithChildren
  OficinaRoute: typeof OficinaRouteWithChildren
  PassageiroRoute: typeof PassageiroRouteWithChildren
  ProprietarioRoute: typeof ProprietarioRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario': {
      id: '/proprietario'
      path: '/proprietario'
      fullPath: '/proprietario'
      preLoaderRoute: typeof ProprietarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passageiro': {
      id: '/passageiro'
      path: '/passageiro'
      fullPath: '/passageiro'
      preLoaderRoute: typeof PassageiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oficina': {
      id: '/oficina'
      path: '/oficina'
      fullPath: '/oficina'
      preLoaderRoute: typeof OficinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista': {
      id: '/motorista'
      path: '/motorista'
      fullPath: '/motorista'
      preLoaderRoute: typeof MotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietario/': {
      id: '/proprietario/'
      path: '/'
      fullPath: '/proprietario/'
      preLoaderRoute: typeof ProprietarioIndexRouteImport
      parentRoute: typeof ProprietarioRoute
    }
    '/passageiro/': {
      id: '/passageiro/'
      path: '/'
      fullPath: '/passageiro/'
      preLoaderRoute: typeof PassageiroIndexRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/oficina/': {
      id: '/oficina/'
      path: '/'
      fullPath: '/oficina/'
      preLoaderRoute: typeof OficinaIndexRouteImport
      parentRoute: typeof OficinaRoute
    }
    '/motorista/': {
      id: '/motorista/'
      path: '/'
      fullPath: '/motorista/'
      preLoaderRoute: typeof MotoristaIndexRouteImport
      parentRoute: typeof MotoristaRoute
    }
    '/loja/': {
      id: '/loja/'
      path: '/'
      fullPath: '/loja/'
      preLoaderRoute: typeof LojaIndexRouteImport
      parentRoute: typeof LojaRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/proprietario/perfil': {
      id: '/proprietario/perfil'
      path: '/perfil'
      fullPath: '/proprietario/perfil'
      preLoaderRoute: typeof ProprietarioPerfilRouteImport
      parentRoute: typeof ProprietarioRoute
    }
    '/proprietario/notificacoes': {
      id: '/proprietario/notificacoes'
      path: '/notificacoes'
      fullPath: '/proprietario/notificacoes'
      preLoaderRoute: typeof ProprietarioNotificacoesRouteImport
      parentRoute: typeof ProprietarioRoute
    }
    '/proprietario/motoristas': {
      id: '/proprietario/motoristas'
      path: '/motoristas'
      fullPath: '/proprietario/motoristas'
      preLoaderRoute: typeof ProprietarioMotoristasRouteImport
      parentRoute: typeof ProprietarioRoute
    }
    '/proprietario/marketplace': {
      id: '/proprietario/marketplace'
      path: '/marketplace'
      fullPath: '/proprietario/marketplace'
      preLoaderRoute: typeof ProprietarioMarketplaceRouteImport
      parentRoute: typeof ProprietarioRoute
    }
    '/proprietario/financeiro': {
      id: '/proprietario/financeiro'
      path: '/financeiro'
      fullPath: '/proprietario/financeiro'
      preLoaderRoute: typeof ProprietarioFinanceiroRouteImport
      parentRoute: typeof ProprietarioRoute
    }
    '/proprietario/agenda': {
      id: '/proprietario/agenda'
      path: '/agenda'
      fullPath: '/proprietario/agenda'
      preLoaderRoute: typeof ProprietarioAgendaRouteImport
      parentRoute: typeof ProprietarioRoute
    }
    '/passageiro/perfil': {
      id: '/passageiro/perfil'
      path: '/perfil'
      fullPath: '/passageiro/perfil'
      preLoaderRoute: typeof PassageiroPerfilRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/parceiros': {
      id: '/passageiro/parceiros'
      path: '/parceiros'
      fullPath: '/passageiro/parceiros'
      preLoaderRoute: typeof PassageiroParceirosRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/passageiro/cashback': {
      id: '/passageiro/cashback'
      path: '/cashback'
      fullPath: '/passageiro/cashback'
      preLoaderRoute: typeof PassageiroCashbackRouteImport
      parentRoute: typeof PassageiroRoute
    }
    '/oficina/perfil': {
      id: '/oficina/perfil'
      path: '/perfil'
      fullPath: '/oficina/perfil'
      preLoaderRoute: typeof OficinaPerfilRouteImport
      parentRoute: typeof OficinaRoute
    }
    '/oficina/financeiro': {
      id: '/oficina/financeiro'
      path: '/financeiro'
      fullPath: '/oficina/financeiro'
      preLoaderRoute: typeof OficinaFinanceiroRouteImport
      parentRoute: typeof OficinaRoute
    }
    '/oficina/agenda': {
      id: '/oficina/agenda'
      path: '/agenda'
      fullPath: '/oficina/agenda'
      preLoaderRoute: typeof OficinaAgendaRouteImport
      parentRoute: typeof OficinaRoute
    }
    '/motorista/perfil': {
      id: '/motorista/perfil'
      path: '/perfil'
      fullPath: '/motorista/perfil'
      preLoaderRoute: typeof MotoristaPerfilRouteImport
      parentRoute: typeof MotoristaRoute
    }
    '/motorista/orcamentos': {
      id: '/motorista/orcamentos'
      path: '/orcamentos'
      fullPath: '/motorista/orcamentos'
      preLoaderRoute: typeof MotoristaOrcamentosRouteImport
      parentRoute: typeof MotoristaRoute
    }
    '/motorista/jornada': {
      id: '/motorista/jornada'
      path: '/jornada'
      fullPath: '/motorista/jornada'
      preLoaderRoute: typeof MotoristaJornadaRouteImport
      parentRoute: typeof MotoristaRoute
    }
    '/motorista/corridas': {
      id: '/motorista/corridas'
      path: '/corridas'
      fullPath: '/motorista/corridas'
      preLoaderRoute: typeof MotoristaCorridasRouteImport
      parentRoute: typeof MotoristaRoute
    }
    '/motorista/checkin': {
      id: '/motorista/checkin'
      path: '/checkin'
      fullPath: '/motorista/checkin'
      preLoaderRoute: typeof MotoristaCheckinRouteImport
      parentRoute: typeof MotoristaRoute
    }
    '/motorista/beneficios': {
      id: '/motorista/beneficios'
      path: '/beneficios'
      fullPath: '/motorista/beneficios'
      preLoaderRoute: typeof MotoristaBeneficiosRouteImport
      parentRoute: typeof MotoristaRoute
    }
    '/motorista/alugueis': {
      id: '/motorista/alugueis'
      path: '/alugueis'
      fullPath: '/motorista/alugueis'
      preLoaderRoute: typeof MotoristaAlugueisRouteImport
      parentRoute: typeof MotoristaRoute
    }
    '/loja/perfil': {
      id: '/loja/perfil'
      path: '/perfil'
      fullPath: '/loja/perfil'
      preLoaderRoute: typeof LojaPerfilRouteImport
      parentRoute: typeof LojaRoute
    }
    '/loja/negocio': {
      id: '/loja/negocio'
      path: '/negocio'
      fullPath: '/loja/negocio'
      preLoaderRoute: typeof LojaNegocioRouteImport
      parentRoute: typeof LojaRoute
    }
    '/loja/estoque': {
      id: '/loja/estoque'
      path: '/estoque'
      fullPath: '/loja/estoque'
      preLoaderRoute: typeof LojaEstoqueRouteImport
      parentRoute: typeof LojaRoute
    }
    '/loja/campanhas': {
      id: '/loja/campanhas'
      path: '/campanhas'
      fullPath: '/loja/campanhas'
      preLoaderRoute: typeof LojaCampanhasRouteImport
      parentRoute: typeof LojaRoute
    }
    '/admin/parceiros': {
      id: '/admin/parceiros'
      path: '/parceiros'
      fullPath: '/admin/parceiros'
      preLoaderRoute: typeof AdminParceirosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderacao': {
      id: '/admin/moderacao'
      path: '/moderacao'
      fullPath: '/admin/moderacao'
      preLoaderRoute: typeof AdminModeracaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/proprietario/frota/': {
      id: '/proprietario/frota/'
      path: '/frota'
      fullPath: '/proprietario/frota/'
      preLoaderRoute: typeof ProprietarioFrotaIndexRouteImport
      parentRoute: typeof ProprietarioRoute
    }
    '/proprietario/contratos/': {
      id: '/proprietario/contratos/'
      path: '/contratos'
      fullPath: '/proprietario/contratos/'
      preLoaderRoute: typeof ProprietarioContratosIndexRouteImport
      parentRoute: typeof ProprietarioRoute
    }
    '/oficina/servicos/': {
      id: '/oficina/servicos/'
      path: '/servicos'
      fullPath: '/oficina/servicos/'
      preLoaderRoute: typeof OficinaServicosIndexRouteImport
      parentRoute: typeof OficinaRoute
    }
    '/loja/catalogo/': {
      id: '/loja/catalogo/'
      path: '/catalogo'
      fullPath: '/loja/catalogo/'
      preLoaderRoute: typeof LojaCatalogoIndexRouteImport
      parentRoute: typeof LojaRoute
    }
    '/proprietario/solicitacoes/$id': {
      id: '/proprietario/solicitacoes/$id'
      path: '/solicitacoes/$id'
      fullPath: '/proprietario/solicitacoes/$id'
      preLoaderRoute: typeof ProprietarioSolicitacoesIdRouteImport
      parentRoute: typeof ProprietarioRoute
    }
    '/proprietario/frota/novo': {
      id: '/proprietario/frota/novo'
      path: '/frota/novo'
      fullPath: '/proprietario/frota/novo'
      preLoaderRoute: typeof ProprietarioFrotaNovoRouteImport
      parentRoute: typeof ProprietarioRoute
    }
    '/proprietario/frota/$carroId': {
      id: '/proprietario/frota/$carroId'
      path: '/frota/$carroId'
      fullPath: '/proprietario/frota/$carroId'
      preLoaderRoute: typeof ProprietarioFrotaCarroIdRouteImport
      parentRoute: typeof ProprietarioRoute
    }
    '/proprietario/contratos/novo': {
      id: '/proprietario/contratos/novo'
      path: '/contratos/novo'
      fullPath: '/proprietario/contratos/novo'
      preLoaderRoute: typeof ProprietarioContratosNovoRouteImport
      parentRoute: typeof ProprietarioRoute
    }
    '/proprietario/contratos/$id': {
      id: '/proprietario/contratos/$id'
      path: '/contratos/$id'
      fullPath: '/proprietario/contratos/$id'
      preLoaderRoute: typeof ProprietarioContratosIdRouteImport
      parentRoute: typeof ProprietarioRoute
    }
    '/oficina/servicos/$osId': {
      id: '/oficina/servicos/$osId'
      path: '/servicos/$osId'
      fullPath: '/oficina/servicos/$osId'
      preLoaderRoute: typeof OficinaServicosOsIdRouteImport
      parentRoute: typeof OficinaRoute
    }
    '/motorista/corridas/$id': {
      id: '/motorista/corridas/$id'
      path: '/$id'
      fullPath: '/motorista/corridas/$id'
      preLoaderRoute: typeof MotoristaCorridasIdRouteImport
      parentRoute: typeof MotoristaCorridasRoute
    }
    '/motorista/beneficios/$parceiroId': {
      id: '/motorista/beneficios/$parceiroId'
      path: '/$parceiroId'
      fullPath: '/motorista/beneficios/$parceiroId'
      preLoaderRoute: typeof MotoristaBeneficiosParceiroIdRouteImport
      parentRoute: typeof MotoristaBeneficiosRoute
    }
    '/motorista/alugueis/$carroId': {
      id: '/motorista/alugueis/$carroId'
      path: '/$carroId'
      fullPath: '/motorista/alugueis/$carroId'
      preLoaderRoute: typeof MotoristaAlugueisCarroIdRouteImport
      parentRoute: typeof MotoristaAlugueisRoute
    }
    '/loja/catalogo/novo': {
      id: '/loja/catalogo/novo'
      path: '/catalogo/novo'
      fullPath: '/loja/catalogo/novo'
      preLoaderRoute: typeof LojaCatalogoNovoRouteImport
      parentRoute: typeof LojaRoute
    }
    '/loja/catalogo/$itemId': {
      id: '/loja/catalogo/$itemId'
      path: '/catalogo/$itemId'
      fullPath: '/loja/catalogo/$itemId'
      preLoaderRoute: typeof LojaCatalogoItemIdRouteImport
      parentRoute: typeof LojaRoute
    }
  }
}

interface AdminRouteChildren {
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminModeracaoRoute: typeof AdminModeracaoRoute
  AdminParceirosRoute: typeof AdminParceirosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminModeracaoRoute: AdminModeracaoRoute,
  AdminParceirosRoute: AdminParceirosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LojaRouteChildren {
  LojaCampanhasRoute: typeof LojaCampanhasRoute
  LojaEstoqueRoute: typeof LojaEstoqueRoute
  LojaNegocioRoute: typeof LojaNegocioRoute
  LojaPerfilRoute: typeof LojaPerfilRoute
  LojaIndexRoute: typeof LojaIndexRoute
  LojaCatalogoItemIdRoute: typeof LojaCatalogoItemIdRoute
  LojaCatalogoNovoRoute: typeof LojaCatalogoNovoRoute
  LojaCatalogoIndexRoute: typeof LojaCatalogoIndexRoute
}

const LojaRouteChildren: LojaRouteChildren = {
  LojaCampanhasRoute: LojaCampanhasRoute,
  LojaEstoqueRoute: LojaEstoqueRoute,
  LojaNegocioRoute: LojaNegocioRoute,
  LojaPerfilRoute: LojaPerfilRoute,
  LojaIndexRoute: LojaIndexRoute,
  LojaCatalogoItemIdRoute: LojaCatalogoItemIdRoute,
  LojaCatalogoNovoRoute: LojaCatalogoNovoRoute,
  LojaCatalogoIndexRoute: LojaCatalogoIndexRoute,
}

const LojaRouteWithChildren = LojaRoute._addFileChildren(LojaRouteChildren)

interface MotoristaAlugueisRouteChildren {
  MotoristaAlugueisCarroIdRoute: typeof MotoristaAlugueisCarroIdRoute
}

const MotoristaAlugueisRouteChildren: MotoristaAlugueisRouteChildren = {
  MotoristaAlugueisCarroIdRoute: MotoristaAlugueisCarroIdRoute,
}

const MotoristaAlugueisRouteWithChildren =
  MotoristaAlugueisRoute._addFileChildren(MotoristaAlugueisRouteChildren)

interface MotoristaBeneficiosRouteChildren {
  MotoristaBeneficiosParceiroIdRoute: typeof MotoristaBeneficiosParceiroIdRoute
}

const MotoristaBeneficiosRouteChildren: MotoristaBeneficiosRouteChildren = {
  MotoristaBeneficiosParceiroIdRoute: MotoristaBeneficiosParceiroIdRoute,
}

const MotoristaBeneficiosRouteWithChildren =
  MotoristaBeneficiosRoute._addFileChildren(MotoristaBeneficiosRouteChildren)

interface MotoristaCorridasRouteChildren {
  MotoristaCorridasIdRoute: typeof MotoristaCorridasIdRoute
}

const MotoristaCorridasRouteChildren: MotoristaCorridasRouteChildren = {
  MotoristaCorridasIdRoute: MotoristaCorridasIdRoute,
}

const MotoristaCorridasRouteWithChildren =
  MotoristaCorridasRoute._addFileChildren(MotoristaCorridasRouteChildren)

interface MotoristaRouteChildren {
  MotoristaAlugueisRoute: typeof MotoristaAlugueisRouteWithChildren
  MotoristaBeneficiosRoute: typeof MotoristaBeneficiosRouteWithChildren
  MotoristaCheckinRoute: typeof MotoristaCheckinRoute
  MotoristaCorridasRoute: typeof MotoristaCorridasRouteWithChildren
  MotoristaJornadaRoute: typeof MotoristaJornadaRoute
  MotoristaOrcamentosRoute: typeof MotoristaOrcamentosRoute
  MotoristaPerfilRoute: typeof MotoristaPerfilRoute
  MotoristaIndexRoute: typeof MotoristaIndexRoute
}

const MotoristaRouteChildren: MotoristaRouteChildren = {
  MotoristaAlugueisRoute: MotoristaAlugueisRouteWithChildren,
  MotoristaBeneficiosRoute: MotoristaBeneficiosRouteWithChildren,
  MotoristaCheckinRoute: MotoristaCheckinRoute,
  MotoristaCorridasRoute: MotoristaCorridasRouteWithChildren,
  MotoristaJornadaRoute: MotoristaJornadaRoute,
  MotoristaOrcamentosRoute: MotoristaOrcamentosRoute,
  MotoristaPerfilRoute: MotoristaPerfilRoute,
  MotoristaIndexRoute: MotoristaIndexRoute,
}

const MotoristaRouteWithChildren = MotoristaRoute._addFileChildren(
  MotoristaRouteChildren,
)

interface OficinaRouteChildren {
  OficinaAgendaRoute: typeof OficinaAgendaRoute
  OficinaFinanceiroRoute: typeof OficinaFinanceiroRoute
  OficinaPerfilRoute: typeof OficinaPerfilRoute
  OficinaIndexRoute: typeof OficinaIndexRoute
  OficinaServicosOsIdRoute: typeof OficinaServicosOsIdRoute
  OficinaServicosIndexRoute: typeof OficinaServicosIndexRoute
}

const OficinaRouteChildren: OficinaRouteChildren = {
  OficinaAgendaRoute: OficinaAgendaRoute,
  OficinaFinanceiroRoute: OficinaFinanceiroRoute,
  OficinaPerfilRoute: OficinaPerfilRoute,
  OficinaIndexRoute: OficinaIndexRoute,
  OficinaServicosOsIdRoute: OficinaServicosOsIdRoute,
  OficinaServicosIndexRoute: OficinaServicosIndexRoute,
}

const OficinaRouteWithChildren =
  OficinaRoute._addFileChildren(OficinaRouteChildren)

interface PassageiroRouteChildren {
  PassageiroCashbackRoute: typeof PassageiroCashbackRoute
  PassageiroParceirosRoute: typeof PassageiroParceirosRoute
  PassageiroPerfilRoute: typeof PassageiroPerfilRoute
  PassageiroIndexRoute: typeof PassageiroIndexRoute
}

const PassageiroRouteChildren: PassageiroRouteChildren = {
  PassageiroCashbackRoute: PassageiroCashbackRoute,
  PassageiroParceirosRoute: PassageiroParceirosRoute,
  PassageiroPerfilRoute: PassageiroPerfilRoute,
  PassageiroIndexRoute: PassageiroIndexRoute,
}

const PassageiroRouteWithChildren = PassageiroRoute._addFileChildren(
  PassageiroRouteChildren,
)

interface ProprietarioRouteChildren {
  ProprietarioAgendaRoute: typeof ProprietarioAgendaRoute
  ProprietarioFinanceiroRoute: typeof ProprietarioFinanceiroRoute
  ProprietarioMarketplaceRoute: typeof ProprietarioMarketplaceRoute
  ProprietarioMotoristasRoute: typeof ProprietarioMotoristasRoute
  ProprietarioNotificacoesRoute: typeof ProprietarioNotificacoesRoute
  ProprietarioPerfilRoute: typeof ProprietarioPerfilRoute
  ProprietarioIndexRoute: typeof ProprietarioIndexRoute
  ProprietarioContratosIdRoute: typeof ProprietarioContratosIdRoute
  ProprietarioContratosNovoRoute: typeof ProprietarioContratosNovoRoute
  ProprietarioFrotaCarroIdRoute: typeof ProprietarioFrotaCarroIdRoute
  ProprietarioFrotaNovoRoute: typeof ProprietarioFrotaNovoRoute
  ProprietarioSolicitacoesIdRoute: typeof ProprietarioSolicitacoesIdRoute
  ProprietarioContratosIndexRoute: typeof ProprietarioContratosIndexRoute
  ProprietarioFrotaIndexRoute: typeof ProprietarioFrotaIndexRoute
}

const ProprietarioRouteChildren: ProprietarioRouteChildren = {
  ProprietarioAgendaRoute: ProprietarioAgendaRoute,
  ProprietarioFinanceiroRoute: ProprietarioFinanceiroRoute,
  ProprietarioMarketplaceRoute: ProprietarioMarketplaceRoute,
  ProprietarioMotoristasRoute: ProprietarioMotoristasRoute,
  ProprietarioNotificacoesRoute: ProprietarioNotificacoesRoute,
  ProprietarioPerfilRoute: ProprietarioPerfilRoute,
  ProprietarioIndexRoute: ProprietarioIndexRoute,
  ProprietarioContratosIdRoute: ProprietarioContratosIdRoute,
  ProprietarioContratosNovoRoute: ProprietarioContratosNovoRoute,
  ProprietarioFrotaCarroIdRoute: ProprietarioFrotaCarroIdRoute,
  ProprietarioFrotaNovoRoute: ProprietarioFrotaNovoRoute,
  ProprietarioSolicitacoesIdRoute: ProprietarioSolicitacoesIdRoute,
  ProprietarioContratosIndexRoute: ProprietarioContratosIndexRoute,
  ProprietarioFrotaIndexRoute: ProprietarioFrotaIndexRoute,
}

const ProprietarioRouteWithChildren = ProprietarioRoute._addFileChildren(
  ProprietarioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  LojaRoute: LojaRouteWithChildren,
  MotoristaRoute: MotoristaRouteWithChildren,
  OficinaRoute: OficinaRouteWithChildren,
  PassageiroRoute: PassageiroRouteWithChildren,
  ProprietarioRoute: ProprietarioRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
